"""Phase 4 analysis: per-family tables, fits, and the five pre-registered kill criteria (PHASE3.md 2.3.8), applied exactly.
Reads results/runs.jsonl (+ labels); writes results/analysis.md and prints it.  Python output is evidence, never proof."""
import os, sys, json, math
from collections import defaultdict
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
INST = os.path.normpath(os.path.join(HERE, '..', 'instances'))
RES = os.path.normpath(os.path.join(HERE, '..', 'results'))
CAP = 3600.0
HOME_TURF = ['F3', 'F4', 'F5', 'F8']


def load_jsonl(p):
    if not os.path.exists(p):
        return []
    out = []
    for l in open(p):
        l = l.strip()
        if l:
            try:
                out.append(json.loads(l))
            except Exception:
                pass
    return out


def main():
    runs = load_jsonl(os.path.join(RES, sys.argv[1] if len(sys.argv) > 1 else 'runs.jsonl'))
    labels = {}
    for r in load_jsonl(os.path.join(INST, 'labels_f12.jsonl')):
        labels[(r['family'], r['name'])] = r['cadical']
    for r in load_jsonl(os.path.join(INST, 'labels_retry.jsonl')):      # longer-timeout retries override first-pass timeouts
        if r['cadical'] in ('SAT', 'UNSAT'):
            labels[(r['family'], r['name'])] = r['cadical']
    for r in load_jsonl(os.path.join(INST, 'sc23', 'labels_f7.jsonl')):
        labels[('F7', r['hash'] + '.cnf')] = r['cadical']
    manifest = load_jsonl(os.path.join(INST, 'MANIFEST.jsonl'))
    listed_sizes = defaultdict(set)
    for r in manifest:
        listed_sizes[r['family']].add(r['size'])
    for r in runs:
        if r['family'] == 'F7':
            listed_sizes['F7'].add(0)
    listed = {f: sorted(s) for f, s in listed_sizes.items()}

    # expected label
    for r in runs:
        lab = r.get('label')
        if lab == 'cadical':
            lab = labels.get((r['family'], r['name']), 'unknown')
        r['expected'] = lab
        r['timeout'] = r.get('status') in ('TIMEOUT', 'TIMEOUT-HARDKILL')
        r['solved'] = r.get('status') in ('SATISFIABLE', 'UNSATISFIABLE')

    md = []
    P = md.append
    P('# Phase 4 analysis (generated by analyze.py)\n')
    P('Runs recorded: %d. Modes: %s.\n' % (len(runs), sorted(set(r['mode'] for r in runs))))

    # ---------------- K1 ----------------
    k1 = []
    for r in runs:
        st = r.get('status')
        if st == 'SATISFIABLE':
            if r.get('model_ok') is False:
                k1.append((r, 'model rejected by independent evaluator: %s' % r.get('model_check')))
            if r['expected'] == 'UNSAT':
                k1.append((r, 'SAT answer on an instance labelled UNSAT'))
        elif st == 'UNSATISFIABLE':
            if r['expected'] == 'SAT':
                k1.append((r, 'UNSAT answer on an instance labelled SAT'))
            dt = r.get('dprtrim', '')
            if dt.startswith('NOT-VERIFIED') and 'TIMEOUT' not in dt:      # a checker timeout is not a rejection
                k1.append((r, 'proof rejected by dpr-trim: %s' % dt))
            pc = r.get('prcheck', '')
            if pc.startswith('FAIL'):
                k1.append((r, 'proof rejected by prcheck.py: %s' % pc))
        elif st == 'CRASH':
            k1.append((r, 'solver crash (recorded, not a wrong answer): %s' % r.get('stderr', '')[:100]))
    P('## K1 (wrong answer / rejected proof)\n')
    wrong = [x for x in k1 if 'crash' not in x[1]]
    P('**K1 fired: %s** (%d wrong answers or rejected proofs; %d crashes recorded separately)\n' % ('YES' if wrong else 'NO', len(wrong), len(k1) - len(wrong)))
    for r, why in k1[:50]:
        P('- %s %s [%s]: %s' % (r['family'], r['name'], r['mode'], why))
    nver = defaultdict(int)
    for r in runs:
        if r.get('status') == 'UNSATISFIABLE':
            nver['unsat_total'] += 1
            if r.get('dprtrim') == 'VERIFIED': nver['dprtrim_verified'] += 1
            elif 'TIMEOUT' in str(r.get('dprtrim')): nver['dprtrim_checker_timeout_1h'] += 1
            else: nver['dprtrim_other'] += 1
            if str(r.get('prcheck', '')).startswith('VERIFIED'): nver['prcheck_verified'] += 1
            if r['expected'] == 'UNSAT': nver['label_agrees'] += 1
            elif r['expected'] == 'unknown': nver['label_unknown'] += 1
        if r.get('status') == 'SATISFIABLE':
            nver['sat_total'] += 1
            if r.get('model_ok'): nver['model_verified'] += 1
            if r['expected'] == 'SAT': nver['sat_label_agrees'] += 1
            elif r['expected'] == 'unknown': nver['sat_label_unknown'] += 1
    P('\nVerification tally: %s\n' % json.dumps(nver))
    cto = [r for r in runs if r.get('status') == 'UNSATISFIABLE' and 'TIMEOUT' in str(r.get('dprtrim'))]
    if cto:
        P("UNSAT answers whose dpr-trim check exceeded the checker's own 3,600 s limit (checker timeouts, not rejections; the answers agree with the construction label or the CaDiCaL label):")
        for r in cto:
            P('- %s %s [%s]: cost %s, expected %s' % (r['family'], r['name'], r['mode'], r.get('cost'), r['expected']))

    # ---------------- per family/size/mode tables ----------------
    groups = defaultdict(list)
    for r in runs:
        groups[(r['family'], r['size'], r['mode'])].append(r)

    def cost_of(r):
        c = r.get('cost')
        return c if c is not None else float('nan')

    def summarize(rs):
        n = len(rs)
        solved = [r for r in rs if r['solved']]
        tos = [r for r in rs if r['timeout']]
        crashes = [r for r in rs if r.get('status') == 'CRASH']
        # censored ordering: timeouts count as +inf
        vals = sorted([(cost_of(r), False) for r in solved] + [(float('inf'), True) for r in tos])
        med = None; censored = False
        if vals:
            k = len(vals) // 2
            if len(vals) % 2 == 1:
                med, censored = vals[k]
            else:
                a, b = vals[k - 1], vals[k]
                censored = a[1] or b[1]
                med = (a[0] + b[0]) / 2 if not censored else (a[0] if not a[1] else min(cost_of(r) for r in tos))
            if censored:
                # lower bound: the smallest cost reached at timeout among the censored runs beyond the median position
                lb = min([cost_of(r) for r in tos] or [float('nan')])
                med = max(med if med != float('inf') else 0, lb)
        mx = max([cost_of(r) for r in solved], default=float('nan'))
        mwall = float(np.median([r.get('wall', float('nan')) for r in solved])) if solved else float('nan')
        return dict(n=n, solved=len(solved), timeouts=len(tos), crashes=len(crashes), median=med, censored=censored, max=mx, median_wall=mwall,
                    verified=sum(1 for r in solved if (r.get('status') == 'SATISFIABLE' and r.get('model_ok')) or (r.get('status') == 'UNSATISFIABLE' and r.get('dprtrim') == 'VERIFIED')),
                    label_ok=sum(1 for r in solved if (r.get('status') == 'SATISFIABLE' and r['expected'] in ('SAT',)) or (r.get('status') == 'UNSATISFIABLE' and r['expected'] in ('UNSAT',))))

    fams = sorted(set(r['family'] for r in runs))
    modes = ['sdcl', 'plain', 'unfiltered']
    summ = {}
    for f in fams:
        P('\n## %s\n' % f)
        P('| size | mode | n | solved | timeouts | crashes | answers verified | label agrees | median cost | max cost | median wall (s) |')
        P('|---|---|---|---|---|---|---|---|---|---|---|')
        for s in listed.get(f, []):
            for m in modes:
                rs = groups.get((f, s, m))
                if not rs:
                    continue
                S = summarize(rs); summ[(f, s, m)] = S
                medtxt = ('>= %.0f (censored)' % S['median']) if S['censored'] else ('%.0f' % S['median'] if S['median'] is not None else '-')
                P('| %s | %s | %d | %d | %d | %d | %d | %d | %s | %s | %s |' % (
                    s, m, S['n'], S['solved'], S['timeouts'], S['crashes'], S['verified'], S['label_ok'], medtxt,
                    ('%.0f' % S['max']) if not math.isnan(S['max']) else '-', ('%.1f' % S['median_wall']) if not math.isnan(S['median_wall']) else '-'))

    # ---------------- K2 ----------------
    P('\n## K2 (home-turf exponential signature, SDCL*, families F3 F4 F5 F8)\n')
    k2_fired = []
    for f in HOME_TURF:
        sizes = listed.get(f, [])
        if not sizes:
            continue
        second_largest = sizes[-2] if len(sizes) >= 2 else sizes[-1]
        rows = []
        prev = None
        es = []
        for s in sizes:
            S = summ.get((f, s, 'sdcl'))
            if S is None:
                rows.append('| %s | (not run) | | |' % s); prev = None; es.append(None); continue
            med = S['median']
            cap_hit = S['timeouts'] > 0
            e = None
            if prev is not None and med and prev[1] and not S['censored'] and not prev[2] and prev[1] > 0 and med > 0:
                e = math.log(med / prev[1]) / math.log(s / prev[0])
            es.append(e)
            rows.append('| %s | %s | %s | %s |' % (s, ('>= %.0f' % med) if S['censored'] else ('%.0f' % med if med is not None else '-'),
                                               ('%.2f' % e) if e is not None else '-', 'YES (%d/%d)' % (S['timeouts'], S['n']) if cap_hit else 'no'))
            if cap_hit and s <= second_largest:
                k2_fired.append('%s: cap hit at size %s (<= second-largest %s): %d of %d runs' % (f, s, second_largest, S['timeouts'], S['n']))
            prev = (s, med, S['censored'])
        for i in range(1, len(es)):
            if es[i - 1] is not None and es[i] is not None and es[i - 1] > 8 and es[i] > 8:
                k2_fired.append('%s: local exponent > 8 at two consecutive sizes (%s, %s): e = %.2f, %.2f' % (f, sizes[i - 1], sizes[i], es[i - 1], es[i]))
        P('\n### %s (second-largest listed size: %s)\n' % (f, second_largest))
        P('| size | median cost (SDCL*) | local exponent e_k | cap hit |')
        P('|---|---|---|---|')
        md.extend(rows)
    P('\n**K2 fired: %s**\n' % ('YES' if k2_fired else 'NO'))
    for x in k2_fired:
        P('- ' + x)

    # ---------------- K3 ----------------
    P('\n## K3 (scaling fits, SDCL*, families with >= 5 fully solved sizes)\n')
    k3_fired = []
    P('| family | fully solved sizes | poly fit: exponent, RSS | exp fit: rate, RSS | smaller RSS | fired |')
    P('|---|---|---|---|---|---|')
    for f in fams:
        pts = []
        for s in listed.get(f, []):
            S = summ.get((f, s, 'sdcl'))
            if S and S['timeouts'] == 0 and S['crashes'] == 0 and S['solved'] == S['n'] and S['n'] > 0 and S['median'] and S['median'] > 0 and s > 0:
                pts.append((s, S['median']))
        if len(pts) < 5:
            P('| %s | %d (%s) | - | - | - | not applicable |' % (f, len(pts), ', '.join(str(p[0]) for p in pts)))
            continue
        x = np.array([p[0] for p in pts], float); y = np.log(np.array([p[1] for p in pts], float))
        A1 = np.vstack([np.log(x), np.ones_like(x)]).T; c1, r1, *_ = np.linalg.lstsq(A1, y, rcond=None)
        A2 = np.vstack([x, np.ones_like(x)]).T; c2, r2, *_ = np.linalg.lstsq(A2, y, rcond=None)
        rss1 = float(np.sum((A1 @ c1 - y) ** 2)); rss2 = float(np.sum((A2 @ c2 - y) ** 2))
        fired = rss2 < rss1 and c1[0] > 6
        if fired:
            k3_fired.append('%s: exponential model has smaller RSS (%.3f vs %.3f) and polynomial exponent %.2f > 6' % (f, rss2, rss1, c1[0]))
        P('| %s | %d (%s) | %.2f, %.3f | %.4f, %.3f | %s | %s |' % (f, len(pts), ', '.join(str(int(p[0])) for p in pts), c1[0], rss1, c2[0], rss2,
                                                           'exp' if rss2 < rss1 else 'poly', 'YES' if fired else 'no'))
    P('\n**K3 fired: %s**\n' % ('YES' if k3_fired else 'NO'))
    for x in k3_fired:
        P('- ' + x)

    # ---------------- K4 ----------------
    P('\n## K4 (no separation from resolution: F1 UNSAT instances at n in {200, 225, 250})\n')
    k4_fired = []
    P('| n | #UNSAT inst. | SDCL* solved/timeouts | SDCL* median cost | plain solved/timeouts | plain median cost | ratio | fired |')
    P('|---|---|---|---|---|---|---|---|')
    for n in (200, 225, 250):
        rs_s = [r for r in runs if r['family'] == 'F1' and r['size'] == n and r['mode'] == 'sdcl' and r['expected'] == 'UNSAT']
        rs_p = [r for r in runs if r['family'] == 'F1' and r['size'] == n and r['mode'] == 'plain' and r['expected'] == 'UNSAT']
        if not rs_s or not rs_p:
            P('| %d | %d | (incomplete) | | | | | |' % (n, len(set(r['name'] for r in rs_s + rs_p))))
            continue
        Ss = summarize(rs_s); Sp = summarize(rs_p)
        fired = None; ratio = None
        if Ss['median'] is not None and Sp['median'] not in (None, 0) and not Sp['censored']:
            ratio = Ss['median'] / Sp['median']
            fired = ratio >= 0.5          # with censoring, the SDCL* median is a lower bound, so >= still holds if fired
        if fired:
            k4_fired.append('F1 n=%d: SDCL* median cost %s%.0f vs plain %.0f (ratio %s%.2f >= 0.5)' % (n, '>= ' if Ss['censored'] else '', Ss['median'], Sp['median'], '>= ' if Ss['censored'] else '', ratio))
        P('| %d | %d | %d/%d | %s%.0f | %d/%d | %s%.0f | %s | %s |' % (n, len(rs_s), Ss['solved'], Ss['timeouts'], '>= ' if Ss['censored'] else '', Ss['median'] or 0,
                                                              Sp['solved'], Sp['timeouts'], '>= ' if Sp['censored'] else '', Sp['median'] or 0,
                                                              ('%s%.2f' % ('>= ' if Ss['censored'] else '', ratio)) if ratio is not None else '-', 'YES' if fired else ('no' if fired is not None else '-')))
    P('\n**K4 fired: %s**\n' % ('YES' if k4_fired else 'NO'))
    for x in k4_fired:
        P('- ' + x)

    # ---------------- K5 ----------------
    P('\n## K5 (budget: > 10%% of instances at a size up to the second-largest listed hit the %d s cap, SDCL*)\n' % int(CAP))
    k5_fired = []
    P('| family | size | n | cap hits | fraction | fired |')
    P('|---|---|---|---|---|---|')
    for f in fams:
        sizes = listed.get(f, [])
        second_largest = sizes[-2] if len(sizes) >= 2 else (sizes[-1] if sizes else None)
        for s in sizes:
            S = summ.get((f, s, 'sdcl'))
            if S is None:
                continue
            frac = S['timeouts'] / S['n'] if S['n'] else 0
            fired = frac > 0.10 and (second_largest is None or s <= second_largest)
            if fired:
                k5_fired.append('%s size %s: %d of %d runs hit the cap (%.0f%%)' % (f, s, S['timeouts'], S['n'], 100 * frac))
            if S['timeouts']:
                P('| %s | %s | %d | %d | %.0f%% | %s |' % (f, s, S['n'], S['timeouts'], 100 * frac, 'YES' if fired else ('no (largest size)' if s > (second_largest or s) else 'no')))
    P('\n**K5 fired: %s**\n' % ('YES' if k5_fired else 'NO'))
    for x in k5_fired:
        P('- ' + x)

    P('\n## Verdict\n')
    fired = {'K1': bool(wrong), 'K2': bool(k2_fired), 'K3': bool(k3_fired), 'K4': bool(k4_fired), 'K5': bool(k5_fired)}
    P('Kill criteria fired: %s' % ', '.join(k for k, v in fired.items() if v) if any(fired.values()) else 'No kill criterion fired on the recorded runs.')
    text = '\n'.join(md)
    open(os.path.join(RES, 'analysis.md'), 'w', encoding='utf-8').write(text)
    print(text)


if __name__ == '__main__':
    main()
