"""Assemble PHASE4.md from: results/analysis.md (analyze.py), results/runs.jsonl, results/runs_sadical.jsonl, schedule_decision.md,
and static text.  Run after the measured runs (or at a checkpoint; the report states what is complete)."""
import os, sys, json, time, subprocess
from collections import defaultdict, Counter

HERE = os.path.dirname(os.path.abspath(__file__))
P4 = os.path.normpath(os.path.join(HERE, '..')); ROOT = os.path.normpath(os.path.join(P4, '..'))
RES = os.path.join(P4, 'results'); INST = os.path.join(P4, 'instances')


def load(p):
    out = []
    if os.path.exists(p):
        for l in open(p):
            try:
                out.append(json.loads(l))
            except Exception:
                pass
    return out


subprocess.run([sys.executable, os.path.join(HERE, 'analyze.py')], capture_output=True, text=True)
analysis = open(os.path.join(RES, 'analysis.md'), encoding='utf-8').read()
# demote the analysis headings under section 4 of this report
analysis = chr(10).join(('#' + l if l.startswith('#') and not l.startswith('# Phase 4 analysis') else l) for l in analysis.splitlines())
analysis = analysis.replace('# Phase 4 analysis (generated by analyze.py)' + chr(10), '')
runs = load(os.path.join(RES, 'runs.jsonl'))
sad = load(os.path.join(RES, 'runs_sadical.jsonl'))
manifest = load(os.path.join(INST, 'MANIFEST.jsonl'))
f7 = [r for r in load(os.path.join(INST, 'sc23', 'labels_f7.jsonl')) if r['cadical'] in ('SAT', 'UNSAT')]
total_jobs = (len(manifest) + len(f7)) * 3
done = Counter(r['mode'] for r in runs)
sched = open(os.path.join(P4, 'schedule_decision.md'), encoding='utf-8').read().strip()
verdict_block = open(os.path.join(P4, 'verdict.md'), encoding='utf-8').read().strip() if os.path.exists(os.path.join(P4, 'verdict.md')) else '(verdict.md missing)'

# supplementary SaDiCaL table
sad_rows = ['| family | instance | size | SaDiCaL result | conflicts | prunes | reducts | wall (s) | dpr-trim |', '|---|---|---|---|---|---|---|---|---|']
for r in sorted(sad, key=lambda r: (r['family'], r['size'], r['name'])):
    if r['status'] == 'UNKNOWN' and r['wall'] >= 3600:
        r['status'] = 'TIMEOUT (3600 s cap)'
    sad_rows.append('| %s | %s | %s | %s | %s | %s | %s | %.1f | %s |' % (r['family'], r['name'], r['size'], r['status'], r.get('conflicts'), r.get('pruned'), r.get('reducts'), r['wall'], r.get('dprtrim', '-')))

# per-mode completion
comp = ['| mode | jobs recorded | of | solved | timeouts | crashes |', '|---|---|---|---|---|---|']
for m in ('sdcl', 'plain', 'unfiltered'):
    rs = [r for r in runs if r['mode'] == m]
    comp.append('| %s | %d | %d | %d | %d | %d |' % (m, len(rs), total_jobs // 3, sum(1 for r in rs if r.get('status') in ('SATISFIABLE', 'UNSATISFIABLE')),
                                                 sum(1 for r in rs if str(r.get('status')).startswith('TIMEOUT')), sum(1 for r in rs if r.get('status') == 'CRASH')))

doc = f"""# PHASE4.md — Falsification of candidate C3 (SDCL\\*, satisfaction-driven clause learning with PR learning)

Session 2026-10-05/06. Pre-registered plan: PHASE3.md §2.3.8 and Appendix C, run exactly as written (no configuration, family, size, count or
kill criterion changed). Everything written before the first measured run is in NOTES.md ("PHASE 4 (2026-10-05)" section): definitions checked
against the papers, implementation decisions, instance manifest with SHA-256 hashes, solver verification, and the F7 list. Project status is
unchanged: **NOT PROVED** (`PvsNP.sat_in_p` is still `sorry`). Python/C++ output is evidence, never proof. Nothing is committed.

Report generated {time.strftime('%Y-%m-%d %H:%M')} from `phase4/results/runs.jsonl` ({len(runs)} of {total_jobs} planned runs recorded).

## 1. Implementation used

**Own implementation of SDCL\\* (`phase4/src/sdcl.cpp`), not the authors' SaDiCaL.** The original SDCL implementation by Kiesl, Heule and Biere
(SaDiCaL, `http://fmv.jku.at/sadical`, version string `00n`) exists and was downloaded, built (WSL Ubuntu 22.04, gcc 11.4) and run, but it does
**not** match the pre-registered configuration in any base-CDCL parameter: it uses a VMTF queue plus dedicated look-ahead decision heuristics
(least-constrained literal at the root, smallest reduced clause elsewhere, witness-literal priority), glue-based restarts, a growing reduction
interval keeping glue ≤ 3 / size ≤ 3, counts prunes as conflicts, has no conflict limit on the inner solver, and prunes only at look-ahead levels
(details and source line references in NOTES.md). PHASE3.md fixes VSIDS 0.95 with phase saving, Luby restarts (unit 100), 1-UIP with
minimisation, reduction every 2,000 conflicts keeping LBD ≤ 2 plus the most active half, no preprocessing, a reduct check before every decision at
level ≥ 1, and an inner plain-CDCL limited to 100 conflicts. SDCL\\* was therefore implemented from scratch (C++17, ~520 lines, MinGW g++ 13.1 `-O3`),
with the three pre-registered variants: `sdcl` (filtered positive reduct, primary), `plain` (ablation i: SDCL step disabled), `unfiltered`
(ablation ii: original positive reduct). SaDiCaL was run only as a **supplementary reference** on the home-turf families (§7); it plays no role in the
kill criteria.

Definitions (NOTES.md has the full check): positive and filtered positive reducts exactly as HKB19 Definitions 3 and 4; the learned clause is the
negation of the decision literals (HKSB17 Thm. 3 / Fig. 1, HKB19 preliminaries), which is the asserting clause the pre-registration backjumps on;
the witness is the inner solver's model of the reduct over the full trail. Implementation choices not fixed by PHASE3.md and decided before measuring:
duplicate-literal/tautology removal at parse time only; the reduct is built from the current formula (original plus learnt clauses); an exact
per-reduct memoisation of single-literal filter tests; and the schedule convention below.

{sched}

**Cost measure** (pre-registered): `conflicts_outer + conflicts_inner + reduct_checks`; wall-clock secondary; cap 3,600 s per run (solver's own
limit; hard kill at 3,700 s). Timeouts are censored: the solver prints its statistics at the cap, so a timed-out run's cost is a lower bound and
medians over sizes containing timeouts are reported as `>=` (censored) and excluded from the fits (Appendix C).

**Verification** (every run, before counting it): SAT answers are evaluated by `check_model.py` (independent evaluator, no shared code);
UNSAT answers are checked by dpr-trim (Heule's DPR checker, commit `2dff405`) on the solver's DPR proof log, and additionally by the own
pure-Python checker `prcheck.py` on proofs up to 3 MB; every F1/F2/F7 instance is labelled by CaDiCaL 1.9.5 (PySAT) with hard subprocess
timeouts; F3–F6 and F8 labels are known by construction. Before any measurement the solver was fuzzed on 300 random and structured formulas against
CaDiCaL (NOTES.md): no disagreement, every model and every proof verified.

## 2. Environment

Windows 11 Pro 10.0.26200, 16 logical CPUs, 137 GB RAM; Python 3.11.9, PySAT 1.9.dev15 (CaDiCaL 1.9.5), CNFgen 0.9.6, networkx 3.2.1, sympy 1.14.0;
MinGW g++ 13.1.0; WSL Ubuntu 22.04 (SaDiCaL only). Driver `phase4/src/run_phase4.py`, 13 concurrent single-threaded solver processes plus
verification, labelling and SaDiCaL jobs on the same machine: wall-clock numbers are under contention (secondary measure).

## 3. Completion status of the pre-registered run plan

{chr(10).join(comp)}

Order of execution (the only thing changed after the first measured run; configuration, instances and criteria are untouched): the first 331 runs in
size order across all families (SDCL\\* and plain). After two checkpoints showed one 13-job batch per hour at the cap (about 85 h for the full plan),
the driver was restarted in staged priority (F3 F4 F5 F8; then the F1 UNSAT instances at n = 200–250 needed by K4; then F6 F2 F7; then the rest of
F1; the unfiltered ablation last) and, from 02:47, in breadth-first rounds (the first instance of every family × size × label × mode group before
the second instance of any group). At each of the three restarts the in-flight runs were killed and later re-run from scratch; killed attempts were
never recorded, so every recorded run is a first completion. Runs not recorded at the stop point (09:08 local) are shown as `(not run)` in the
tables below, never as solved or failed.

## 4. Results per family, fits and kill criteria (generated by `phase4/src/analyze.py`)

{analysis}

## 5. Verdict

{verdict_block}

## 6. Censoring and other recording notes

* Every run is in `phase4/results/runs.jsonl` (status, cost, conflicts, inner conflicts, reduct checks, PR clauses, decisions, propagations, filter
  statistics, wall-clock, verification results); solver outputs in `phase4/results/out/<family>/`; verified UNSAT proofs up to 20 MB kept in
  `phase4/results/proofs/<family>/` (larger proofs were deleted after verification to save disk; the verification result is recorded).
* Timeouts: the solver stops at its own 3,600 s limit and reports its statistics; `TIMEOUT-HARDKILL` marks the rare case where the 3,700 s hard kill fired
  (no statistics). Both count as cap hits for K2 and K5 and as censored observations for medians.
* No recorded run was omitted, edited or replaced; no parameter was changed after the first measured run. The driver was restarted three times to
  change only the execution order (section 3). The three UNSAT answers whose dpr-trim check exceeded the checker's own 1 h limit are listed under K1.

## 7. Supplementary: the original SaDiCaL on the home-turf families (not part of the kill criteria)

SaDiCaL default options, text DPR proof output (`--no-binary`), 3,600 s cap (`timeout 3600` inside WSL; the runner's own 3,720 s kill is recorded as `TIMEOUT`), two concurrent runs under WSL; proofs checked with dpr-trim. `UNKNOWN` = SaDiCaL exited without an answer line (at the cap, or earlier: `cliquecol_n12` exited after 108 s with 30,816 conflicts and no result; raw output in `phase4/results/out/`). `None` in the dpr-trim column = proof file not present when the check ran (not checked). SaDiCaL's cost is not comparable to SDCL\*'s (different search; inner conflicts not reported); the table shows that short PR proofs of these instances are findable in practice.

{chr(10).join(sad_rows)}
"""
open(os.path.join(ROOT, 'PHASE4.md'), 'w', encoding='utf-8', newline='\n').write(doc)
print('PHASE4.md written:', len(doc.splitlines()), 'lines; runs', len(runs), 'of', total_jobs)
