import Sit

set_option autoImplicit false
open PvsNP.Sit PvsNP.SATDef

#print axioms PvsNP.Sit.Faithful
#print axioms PvsNP.Sit.FamOK
#print axioms PvsNP.Sit.FamPos
#print axioms PvsNP.Sit.FamPos.ok
#print axioms PvsNP.Sit.clauseSat_iff
#print axioms PvsNP.Sit.lookup_of_mem
#print axioms PvsNP.Sit.faithful_of_pol
#print axioms PvsNP.Sit.faithful_pos
#print axioms PvsNP.Sit.faithful_single
#print axioms PvsNP.Sit.Inc.ge
#print axioms PvsNP.Sit.faithful_of_inc
#print axioms PvsNP.Sit.sat_allTrue
#print axioms PvsNP.Sit.FamPos.allTrue
#print axioms PvsNP.Sit.lt_numVars
#print axioms PvsNP.Sit.fam_pos
#print axioms PvsNP.Sit.sh_pos
#print axioms PvsNP.Sit.Enc.enc_lt
#print axioms PvsNP.Sit.Enc.xIdx_lt
#print axioms PvsNP.Sit.Enc.cIdx_lt
#print axioms PvsNP.Sit.Enc.upd_pos
#print axioms PvsNP.Sit.Enc.sdef_pos
#print axioms PvsNP.Sit.Enc.shift_pos
#print axioms PvsNP.Sit.Enc.init_pos
#print axioms PvsNP.Sit.Enc.acode
#print axioms PvsNP.Sit.Enc.accCode
#print axioms PvsNP.Sit.Enc.accCell
#print axioms PvsNP.Sit.Enc.accFamily
#print axioms PvsNP.Sit.Enc.acc_ok
#print axioms PvsNP.Sit.Enc.unit_pol
#print axioms PvsNP.Sit.Enc.acc_code
#print axioms PvsNP.Sit.Enc.acc_cell
#print axioms PvsNP.Sit.Accepts
#print axioms PvsNP.Sit.Enc.accept_sound
#print axioms PvsNP.Sit.Enc.unsat_of_noAccept
#print axioms PvsNP.Sit.Enc.trans_allTrue
#print axioms PvsNP.Sit.Enc.A0_two
#print axioms PvsNP.Sit.Enc.accFamily_allTrue
#print axioms PvsNP.Sit.runI_succ'
#print axioms PvsNP.Sit.iterate_bind_none
#print axioms PvsNP.Sit.runI_of_iterate
#print axioms PvsNP.Sit.runI_add
#print axioms PvsNP.Sit.runI_halted
#print axioms PvsNP.Sit.runI_haltList
#print axioms PvsNP.Sit.accepts_haltList
